### ISSUE TITLE
It doesn't work with more groups

### ISSUE THREAD

**Issue by raufemm** [DevExpress-Examples/dxdatagrid-how-to-implement-a-three-state-select-all-check-box-for-in-a-group-row-t444368#2]
When I put one more group of data, a bug appears. The selection of checkbox doesn't happen if a checkbox with the same name exists. Look on print screen. Subcategory is selected in first time, however on second time is not selected.

What can I do to resolve this bug?

![error](https://user-images.githubusercontent.com/16339798/39526094-2649960a-4df4-11e8-87cb-964e3476bea5.png)

**Comment by artem-kurchenko** [comment]
Hi,
 
I cannot reproduce the issue using our online example (see the [screencast](https://www.dropbox.com/s/yapo77rsssbso4o/T444368.mp4?dl=0)). However, our original example doesn't have the "SubCategory" column. Would you please describe how to reproduce the issue from scratch in greater detail? For instance, you can attach here the modified project illustrating the problem in action.

**Comment by raufemm** [comment]
Hi @artem-kurchenko 

Thanks for your help. I made another example where the same bug happens.

Note that a have Subcategory repeteat in 2 categories. If I have the same Subcategory repeteaed more that once only the first checkbox will is checked.

Please look the printscreen on zip file
[Datagrid.zip](https://github.com/DevExpress-Examples/dxdatagrid-how-to-implement-a-three-state-select-all-check-box-for-in-a-group-row-t444368/files/1973000/Datagrid.zip)
![error_example](https://user-images.githubusercontent.com/16339798/39608141-cebcfd0a-4f15-11e8-8777-c428cda040c1.png)

For exemple, if you check "Group Code 1", The correct is that all the check boxes are checked but it does not occors, only is checked the first subcategory.

If you have more doubts, please contact me.

**Comment by artem-kurchenko** [comment]
Thank you for the example. The problem occurs because these checkboxes have the same id.
The following lines illustrate where this logic is used:
[#1](https://github.com/DevExpress-Examples/dxdatagrid-how-to-implement-a-three-state-select-all-check-box-for-in-a-group-row-t444368/blob/16.1.6%2B/JS/GroupSelectionHelper.js#L14)
[#2](https://github.com/DevExpress-Examples/dxdatagrid-how-to-implement-a-three-state-select-all-check-box-for-in-a-group-row-t444368/blob/16.1.6%2B/JS/GroupSelectionHelper.js#L126)
It's necessary to re-implement this logic to support nested groups with the same keys to resolve this issue.
Try this idea and let us know your results
